name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip \
            openjdk-17-jdk unzip git zip \
            libffi-dev libssl-dev \
            autoconf automake libtool \
            pkg-config zlib1g-dev

          pip install --upgrade pip
          pip install cython buildozer

      - name: Initialize buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: calculator-apk
          path: bin/*.apk
